name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    env:
      FORCE_COLOR: "1"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.10"

      - name: Upgrade pip and nox
        run: |
          pip install -U pip nox
          pip --version

      - name: Build package
        run: |
          nox -s build

      - name: Publish package on PyPI
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
