name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: |
          pip install -U pip
          pip --version

      - name: Build package
        run: |
          pip install build
          python -m build

      - name: Publish package on PyPI
        if: startsWith(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Publish package on TestPyPI
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/

      - name: Publish the release notes
        uses: release-drafter/release-drafter@v5.25.0
        with:
          publish: startsWith(github.ref, 'refs/tags/')
          tag: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
